name: Deploy SpookySpot
on:
  push:
    branches: [ main ]  # or whatever your main branch is

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/projects/aa-projects/spookyspot
            git pull
            docker-compose pull
            docker-compose build --no-cache
            docker-compose up -d
            docker image prune -f